version: '{build}'
image: macos
environment:
  global:
    HAXELIB_ROOT: /Users/appveyor/haxelib

install:
  - cd /Users/appveyor
  - brew install haxe@4.1.5 -y
  - brew install gnutar -y
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime 7.9.0
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib install linc_luajit
  - haxelib list
  - cd /Users/appveyor/projects/kade-engine-macos

build_script:
  - haxelib run lime build mac

after_build:
  - gtar -cvf funkin-ke.tar -C /Users/appveyor/projects/kade-engine-macos/export/release/linux/bin .

artifacts:
- path: funkin-ke.tar
  name: macOS build idk
